name: workflow-name
on: push

jobs:
  job-name:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: SSH to GitHub Actions
        run: |
          pacman -Syu openssh tmate
          ssh-keygen -N "" -f ~/.ssh/id_rsa
          tmate
