name: workflow-name
on: push

jobs:
  job-name:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: SSH to GitHub Actions
        run: |
          whoami
          pacman -Syu --noconfirm openssh tmate
          ssh-keygen -N "" -f /root/.ssh/id_rsa
          tmate new-session -s root
